kumuluzee:
  datasources:
    - jndi-name: jdbc/CustomersDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/customers
      username: postgres
      password: postgres
      max-pool-size: 20